server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@hustevent.vvx1bp9.mongodb.net/?retryWrites=true&w=majority&appName=HustEvent
      database: HustEvent
      username: root
      password: root
  main:
    allow-bean-definition-overriding: true