server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb+srv://kientranduc1:ghk4VcJU7DLkaHRn@husteventv2.kmq9zzw.mongodb.net/?retryWrites=true&w=majority&appName=HustEventV2
      database: HustEventV2
      username: root
      password: root
  main:
    allow-bean-definition-overriding: true

cloudinary:
  cloud-name: dcpz6bqyl
  api-key: 832475981822277
  api-secret: 0hn_kdhvvll9Iaw-8dijdJ4xYZQ